name: scala_dab_example_deploy

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "src/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Jar
        run: sbt package
      - uses: databricks/setup-cli@main
      - run: databricks bundle validate
        env:
          DATABRICKS_TOKEN: 'dapiaefd52ad2776c392701419d401a7665c'
          DATABRICKS_BUNDLE_ENV: dev


