name: scala_dab_example_deploy

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "dlt_with_expectations/**"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: databricks version