name: scala_dab_example_deploy

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "src/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Jar
        run: sbt package
      - uses: databricks/setup-cli@main
      - name: Upload Jar
        uses: databricks/upload-dbfs-temp@v0
        id: upload_app_jar
        with:
              local-path: 'target/scala-2.12/scala-sbt-dab_2.12-0.1.0-SNAPSHOT.jar'

      - run: databricks bundle deploy
        env:
          DATABRICKS_TOKEN: ${{ secrets.DEV_DB_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
          FILE: 'target/scala-2.12/scala-sbt-dab_2.12-0.1.0-SNAPSHOT.jar'


